name = "Hugo-owaraicub"
license = "MIT"
licenselink = "https://github.com/tcgriffith/hugo-owaraiclub/blob/master/LICENSE"
description = "A simple hugo theme inspired by hugo-xmag"
homepage = "https://github.com/tcgriffith/hugo-owaraiclub/"
tags = ["blog", "minimal"]
features = ["responsive", "wiki"]
min_version = "0.58"

[author]
  name = "TC"
  homepage = "https://tc.rbind.io"
