name = "Hugo-owaraicub"
license = "MIT"
licenselink = "https://github.com/tcgriffith/hugo-owaraiclub/blob/master/LICENSE"
description = "A site for variety shows/talents/"
homepage = "https://github.com/tcgriffith/hugo-owaraiclub/"
tags = [minimal, xmag]
features = [responsive, no-js, githubwiki]
min_version = "0.41"

[author]
  name = "TC"
  homepage = "https://tc.rbind.io"
